version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=postit_postgres
      - POSTGRES_USER=api-admin
      - POSTGRES_PASSWORD=api-admin
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# version: '3.8'
# services:
#   db:
#     # env_file:
#     #   - path: "./.env.local"
#     image: postgres:14
#     container_name: postit_db
#     # build:
#     #   context: .
#     #   dockerfile: Dockerfile
#     restart: always
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=api-admin
#       - POSTGRES_PASSWORD=api-admin
#     ports:
#       - "5433:5433"
#     volumes:
#       - postit-postgres-data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postit-postgres-data: